num1=float(input("ingrese el primer numero:"))
num2=float(input("ingrese el segundo numero:"))
num3=float(input("ingrese el tercer numero:"))
print (num1/num2)
print (num1/num3)
print (num2/num1)
print (num2/num3)
print (num3/num1)
print (num3/num2)